
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 10 23:22:22 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATER_OR_EQUAL = 23;
  public static final int INCREMENT = 29;
  public static final int R_SQUARE_BRACKETS = 38;
  public static final int CONST = 7;
  public static final int SLASH = 48;
  public static final int NUMCONST = 42;
  public static final int NOT_EQUAL = 21;
  public static final int LPAREN = 35;
  public static final int GREATER = 22;
  public static final int SEMI = 31;
  public static final int CONTINUE = 17;
  public static final int MINUS = 46;
  public static final int LESS = 24;
  public static final int DECREMENT = 30;
  public static final int STAR = 47;
  public static final int RPAREN = 36;
  public static final int AND = 26;
  public static final int RECORD = 19;
  public static final int LESS_OR_EQUAL = 25;
  public static final int L_SQUARE_BRACKETS = 37;
  public static final int OR = 27;
  public static final int COMMA = 33;
  public static final int CLASS = 4;
  public static final int PLUS = 45;
  public static final int IF = 8;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 28;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int PERCENT = 49;
  public static final int DOUBLE_EQUAL = 20;
  public static final int IDENT = 41;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int COLON = 32;
  public static final int LBRACE = 39;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int GOTO = 18;
  public static final int CHARCONST = 43;
  public static final int WHILE = 10;
  public static final int RBRACE = 40;
  public static final int BOOLCONST = 44;
  public static final int EXTENDS = 16;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

